drop table ticket;
drop table payment;
drop table snackorder;
drop table snack;
drop table seat;
drop table schedule;
drop table theater;
drop table movie;
drop table customer;

DROP SEQUENCE CUSTOMER_SEQ;
DROP SEQUENCE SNACK_SEQ;
DROP SEQUENCE SNACKORDER_SEQ;
DROP SEQUENCE MOVIE_SEQ;
DROP SEQUENCE THEATER_SEQ;
DROP SEQUENCE SCHEDULE_SEQ;
DROP SEQUENCE TICKET_SEQ;
DROP SEQUENCE PAYMENT_SEQ;

-- 회원
CREATE TABLE "CUSTOMER" (
	"CNUM"  NUMBER(8)   CONSTRAINT "PK_CUSTOMER" PRIMARY KEY, -- 회원번호
	"CID"   VARCHAR2(30) UNIQUE NOT NULL, -- 아이디
	"CPW"   VARCHAR2(30) NOT NULL, -- 비밀번호
	"CNAME" VARCHAR2(20) NOT NULL, -- 이름
	"CTEL"  VARCHAR2(20) NOT NULL  -- 전화번호
);

--회원번호
CREATE SEQUENCE CUSTOMER_SEQ
START WITH 1001
NOCACHE;

-- 간식
CREATE TABLE "SNACK" (
	"SNUM"   NUMBER(8)    CONSTRAINT "PK_SNACK" PRIMARY KEY, -- 간식번호
	"STYPE"  VARCHAR2(50) NOT NULL, -- 종류
	"SNAME"  VARCHAR2(50) NOT NULL, -- 이름
	"SPRICE" NUMBER(10)   NOT NULL  -- 가격
);

--간식번호
CREATE SEQUENCE SNACK_SEQ
START WITH 1
NOCACHE;

-- 간식주문
CREATE TABLE "SNACKORDER" (
	"SONUM"  NUMBER(8) CONSTRAINT "PK_SNACKORDER" PRIMARY KEY, -- 간식주문번호
	"POPNUM"   NUMBER(8)  CONSTRAINT "FK_SNUM_SNACKORDER" REFERENCES SNACK(SNUM), -- 팝콘번호
	"POPCNT" NUMBER(2) , -- 팝콘수량
	"BNUM"  NUMBER(8) CONSTRAINT "FK_SNUM2_SNACKORDER" REFERENCES SNACK(SNUM), -- 음료번호
	"BCNT" NUMBER(2) ,  -- 음료수량
    "STCNT" NUMBER(10) NOT NULL, -- 간식총금액
    "CNUM" NUMBER(8) CONSTRAINT "FK_CNUM_SNACKORDER" REFERENCES CUSTOMER(CNUM), --회원번호
    "SOSTATUS" NUMBER(2) NOT NULL  --결제상태 0이면 결제전/ 결제상태 1이면 결제후
    );
    

--간식주문번호
CREATE SEQUENCE SNACKORDER_SEQ
START WITH 10000
NOCACHE;

-- 영화
CREATE TABLE "MOVIE" (
	"MNUM"  NUMBER(8)   CONSTRAINT "PK_MOVIE" PRIMARY KEY, -- 영화번호
	"TITLE" VARCHAR2(30) NOT NULL,  -- 영화제목
    "RUNTIME" NUMBER(4) NOT NULL, --러닝타임
    "MSTARTDATE" CHAR(8) NOT NULL, --상영시작일자
    "MCLOSEDATE" CHAR(8) NOT NULL --상영마감일자
);

--영화번호
CREATE SEQUENCE MOVIE_SEQ
START WITH 100
NOCACHE;

-- 상영관
CREATE TABLE "THEATER" (
	"THNUM"   NUMBER(8) CONSTRAINT "PK_THEATER" PRIMARY KEY, -- 상영관번호
	"TOTSEAT" NUMBER(4) NULL      -- 총좌석수
);

--상영관번호
CREATE SEQUENCE THEATER_SEQ
START WITH 1
NOCACHE;

-- 좌석
CREATE TABLE "SEAT" (
	"SEATNUM"    NUMBER(4) NOT NULL, -- 좌석번호
	"THNUM"      NUMBER(8) CONSTRAINT "FK_THNUM_SEAT" REFERENCES THEATER(THNUM), -- 상영관번호
	"SEATSTATUS" NUMBER(2) NOT NULL     -- 좌석배정유무 (0이면 예약가능/1이면 예약불가능)
);

-- 상영일정
CREATE TABLE "SCHEDULE" (
	"SCNUM"       NUMBER(8) CONSTRAINT "PK_SCHEDULE" PRIMARY KEY, -- 상영일정번호
	"MNUM"        NUMBER(8) CONSTRAINT "FK_MNUM_SCHEDULE" REFERENCES MOVIE(MNUM), -- 영화번호
	"THNUM"       NUMBER(8) CONSTRAINT "FK_THNUM_SCHEDULE" REFERENCES THEATER(THNUM), -- 상영관번호
	"SCDATE" CHAR(8)  NOT NULL, -- 상영일자
	"SCTIME"  CHAR(4) NOT NULL  -- 상영시작시간
);

--상영일정번호
CREATE SEQUENCE SCHEDULE_SEQ
START WITH 1
NOCACHE;

-- 티켓
CREATE TABLE "TICKET" (
	"TNUM"    NUMBER(8)  CONSTRAINT "PK_TICKET" PRIMARY KEY , -- 티켓번호
	"SCNUM"   NUMBER(8)  CONSTRAINT "FK_SCNUM_TICKET" REFERENCES SCHEDULE(SCNUM), -- 상영일정번호
	"THNUM"   NUMBER(8) CONSTRAINT "FK_THNUM_TICKET" REFERENCES THEATER(THNUM), -- 상영관번호
    "SEATNUM" NUMBER(4) NOT NULL, --좌석번호
	"CNUM"    NUMBER(8)  CONSTRAINT "FK_CNUM_TICKET" REFERENCES CUSTOMER(CNUM), -- 회원번호
	"TPRICE"  NUMBER(10) NOT NULL,  -- 가격
    "PAYSTATUS" NUMBER(2) NOT NULL --결제유무 (0 이면 결제 전 / 1이면 결제 후) 
);

--티켓번호
CREATE SEQUENCE TICKET_SEQ
START WITH 100
NOCACHE;

-- 결제
CREATE TABLE "PAYMENT" (
	"PNUM"     NUMBER(8)  CONSTRAINT "PK_PAYMENT" PRIMARY KEY, -- 결제번호
	"CNUM"     NUMBER(8)  CONSTRAINT "FK_CNUM_PAYMENT" REFERENCES CUSTOMER(CNUM), -- 회원번호
	"SONUM"    NUMBER(8)  CONSTRAINT "FK_SONUM_PAYMENT" REFERENCES SNACKORDER(SONUM), -- 간식주문번호
	"TOTPRICE" NUMBER(10) NOT NULL, -- 결제금액
	"PDAY"     DATE       NOT NULL  -- 결제일자
);

--결제번호
CREATE SEQUENCE PAYMENT_SEQ
START WITH 100000
NOCACHE;

--상영관 등록 ( 3개)
INSERT INTO THEATER VALUES(THEATER_SEQ.NEXTVAL,10);
INSERT INTO THEATER VALUES(THEATER_SEQ.NEXTVAL,10);
INSERT INTO THEATER VALUES(THEATER_SEQ.NEXTVAL,10);
INSERT INTO THEATER VALUES(THEATER_SEQ.NEXTVAL,10);
INSERT INTO THEATER VALUES(THEATER_SEQ.NEXTVAL,10);
INSERT INTO THEATER VALUES(THEATER_SEQ.NEXTVAL,10);

--상영관 좌석 등록(25개씩)
INSERT INTO SEAT VALUES(1,1,0);
INSERT INTO SEAT VALUES(2,1,0);
INSERT INTO SEAT VALUES(3,1,0);
INSERT INTO SEAT VALUES(4,1,0);
INSERT INTO SEAT VALUES(5,1,0);
INSERT INTO SEAT VALUES(6,1,0);
INSERT INTO SEAT VALUES(7,1,0);
INSERT INTO SEAT VALUES(8,1,0);
INSERT INTO SEAT VALUES(9,1,0);
INSERT INTO SEAT VALUES(10,1,0);

INSERT INTO SEAT VALUES(1,2,0);
INSERT INTO SEAT VALUES(2,2,0);
INSERT INTO SEAT VALUES(3,2,0);
INSERT INTO SEAT VALUES(4,2,0);
INSERT INTO SEAT VALUES(5,2,0);
INSERT INTO SEAT VALUES(6,2,0);
INSERT INTO SEAT VALUES(7,2,0);
INSERT INTO SEAT VALUES(8,2,0);
INSERT INTO SEAT VALUES(9,2,0);
INSERT INTO SEAT VALUES(10,2,0);

INSERT INTO SEAT VALUES(1,3,0);
INSERT INTO SEAT VALUES(2,3,0);
INSERT INTO SEAT VALUES(3,3,0);
INSERT INTO SEAT VALUES(4,3,0);
INSERT INTO SEAT VALUES(5,3,0);
INSERT INTO SEAT VALUES(6,3,0);
INSERT INTO SEAT VALUES(7,3,0);
INSERT INTO SEAT VALUES(8,3,0);
INSERT INTO SEAT VALUES(9,3,0);
INSERT INTO SEAT VALUES(10,3,0);

INSERT INTO SEAT VALUES(1,4,0);
INSERT INTO SEAT VALUES(2,4,0);
INSERT INTO SEAT VALUES(3,4,0);
INSERT INTO SEAT VALUES(4,4,0);
INSERT INTO SEAT VALUES(5,4,0);
INSERT INTO SEAT VALUES(6,4,0);
INSERT INTO SEAT VALUES(7,4,0);
INSERT INTO SEAT VALUES(8,4,0);
INSERT INTO SEAT VALUES(9,4,0);
INSERT INTO SEAT VALUES(10,4,0);

INSERT INTO SEAT VALUES(1,5,0);
INSERT INTO SEAT VALUES(2,5,0);
INSERT INTO SEAT VALUES(3,5,0);
INSERT INTO SEAT VALUES(4,5,0);
INSERT INTO SEAT VALUES(5,5,0);
INSERT INTO SEAT VALUES(6,5,0);
INSERT INTO SEAT VALUES(7,5,0);
INSERT INTO SEAT VALUES(8,5,0);
INSERT INTO SEAT VALUES(9,5,0);
INSERT INTO SEAT VALUES(10,5,0);

INSERT INTO SEAT VALUES(1,6,0);
INSERT INTO SEAT VALUES(2,6,0);
INSERT INTO SEAT VALUES(3,6,0);
INSERT INTO SEAT VALUES(4,6,0);
INSERT INTO SEAT VALUES(5,6,0);
INSERT INTO SEAT VALUES(6,6,0);
INSERT INTO SEAT VALUES(7,6,0);
INSERT INTO SEAT VALUES(8,6,0);
INSERT INTO SEAT VALUES(9,6,0);
INSERT INTO SEAT VALUES(10,6,0);

--간식등록
INSERT INTO SNACK VALUES(SNACK_SEQ.NEXTVAL,'팝콘','일반 팝콘',5000);
INSERT INTO SNACK VALUES(SNACK_SEQ.NEXTVAL,'팝콘','카라멜 팝콘',6000);
INSERT INTO SNACK VALUES(SNACK_SEQ.NEXTVAL,'팝콘','치즈맛 팝콘',7000);

INSERT INTO SNACK VALUES(SNACK_SEQ.NEXTVAL,'음료','콜라',3000);
INSERT INTO SNACK VALUES(SNACK_SEQ.NEXTVAL,'음료','사이다',3000);
INSERT INTO SNACK VALUES(SNACK_SEQ.NEXTVAL,'음료','오렌지주스',4000);

--영화등록
INSERT INTO MOVIE VALUES(MOVIE_SEQ.NEXTVAL,'바비','120',20230820,20231020);
INSERT INTO MOVIE VALUES(MOVIE_SEQ.NEXTVAL,'밀수','180',20230810,20231120);
INSERT INTO MOVIE VALUES(MOVIE_SEQ.NEXTVAL,'엘리멘탈','190',20230810,20231022);
INSERT INTO MOVIE VALUES(MOVIE_SEQ.NEXTVAL,'오펜하이머','180',20230815,20231010);

--상영일정등록
INSERT INTO SCHEDULE VALUES(SCHEDULE_SEQ.NEXTVAL,100,1,20230820,1300);
INSERT INTO SCHEDULE VALUES(SCHEDULE_SEQ.NEXTVAL,101,2,20230830,1100);
INSERT INTO SCHEDULE VALUES(SCHEDULE_SEQ.NEXTVAL,102,3,20230825,1530);
INSERT INTO SCHEDULE VALUES(SCHEDULE_SEQ.NEXTVAL,100,4,20230824,1410);
INSERT INTO SCHEDULE VALUES(SCHEDULE_SEQ.NEXTVAL,101,5,20230824,1000);
INSERT INTO SCHEDULE VALUES(SCHEDULE_SEQ.NEXTVAL,102,6,20230827,1630);

--관리자등록
INSERT INTO CUSTOMER VALUES(1000,'admin','admin','admin','admin');

commit;